### PR TITLE
added support for apple touch icon

### PR DESCRIPTION
**Pull request by HydaspisChaos**
I added support for an Apple touch icon. This allows us to add the web client to the homescreen of an iPhone or iPad, while displaying a proper icon. I used this icon: https://github.com/badaix/snapcast/blob/master/doc/web_hi_res_512.png and renamed it accordingly. Seems to work fine on my devices.

IMG_8C4B42DAD75B-1

### CODE REVIEW

**Comment by HydaspisChaos** [comment]
The cool thing about this is, that this function basically wraps the web client into an app like container (see https://developer.apple.com/library/archive/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html). If you would like, i can improve the docs at the main project, because this basically brings it on par with the Android offering.

**Comment by badaix** [comment]
Thanks, looks good! 
The icon with the drop shadow is outdated (it was following an old Android style guide). You can find a 512x512 icon here: https://github.com/badaix/snapdroid/blob/develop/Snapcast/src/main/ic_launcher-web.png.
Also the background should not be a circle, but a round rect: https://medium.com/swlh/thoughts-on-the-new-official-apple-app-icon-template-3cc096206082. Can you change this?
Please add the icon also to the Makefile and a small how-to get the web client to the homescreen in the Readme.md

**Comment by badaix** [comment]
I've added a rectangular shaped icon in different resolutions (as listed on the linked page: 152x153, 180x180, 167x167) in develop branch in `dev/images/` directory. I guess that iOS will mask them to a round rect shape. 
Can you please try if these icons will be rendered as round rect?

**Comment by HydaspisChaos** [comment]
I think that the round-rect needs to be incorporated into the icon itself. Right now it looks rather ugly (see attached screenshot). I will play around with it a little bit and come back to you.
IMG_3411

**Comment by badaix** [comment]
I removed the background layer and changed the global image background to yellow in the develop branch. Maybe this will look better

**Comment by badaix** [comment]
abandoned

**Pull request closed without merging**
