### PR TITLE
Add Dependabot

### PR DESCRIPTION
**Pull request by yubiuser**
This will add [Dependabot](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file) to this repo. 
It will open PRs for outdated dependencies. I added the `npm` and `actions` ecosystems, targeting `react` only (this needs to be changed once `react` has been merged to `master`). It will run only once a week, opening up to 10 PRs

### CODE REVIEW

**Comment by yubiuser** [comment]
P.S. This need to go to `master` branch (default branch) to install dependabot, even when only `react` is targeted.

**Comment by badaix** [comment]
Great, thanks, I hope that I find enough time to release the react version with Snapcast v0.28 before Easter. Latest then I will merge it back to main.

**Comment by yubiuser** [comment]
As you seen with all the new PRs, you already merged it into master. But dependabot will only check and update to brach `react`

**Comment by badaix** [comment]
Yep, it's working :) 
I've added grouping to have all Dependabot PRs merged into one.

**Pull request merged**
